# MCP Standalone Infrastructure Services
# For running the MCP server with local data persistence
# Usage: cd docker/mcp-standalone && docker compose up -d

services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-passw0rd}
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_server_memory_heap_initial__size=${NEO4J_HEAP_INITIAL:-512m}
      - NEO4J_server_memory_heap_max__size=${NEO4J_HEAP_MAX:-1G}
      - NEO4J_server_memory_pagecache_size=${NEO4J_PAGECACHE:-512m}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./graphs:/var/lib/neo4j/import/graphs
    networks:
      - lila-network
    restart: unless-stopped
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Admin Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-lila_admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-lila_secure_storage_2025}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lila-network
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache and Session Store
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - lila-network
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

# Named Volumes for Data Persistence
volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

# Network Configuration
networks:
  lila-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16